//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5466
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFACW0001 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PFACW0001.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert into cdifac.tfac042 (gcicod,ftifac,ffsine, ffaine, ffmine, ffdine, ffsfie, ffafie, ffmfie, ffdfie, fhoenv, ffsopr, ffaopr, ffmopr, ffdopr, fusopr, fnuenv, gnufac)
        ///values (&apos;{0}&apos;,&apos;{1}&apos;,&apos;{2}&apos;,&apos;{3}&apos;,&apos;{4}&apos;,&apos;{5}&apos;,&apos;{6}&apos;,&apos;{7}&apos;,&apos;{8}&apos;,&apos;{9}&apos;,&apos;{10}&apos;,&apos;{11}&apos;,&apos;{12}&apos;,&apos;{13}&apos;,&apos;{14}&apos;,&apos;{15}&apos;,{16},&apos;{17}&apos;).
        /// </summary>
        internal static string AlmacenaDocumentoEnvio {
            get {
                return ResourceManager.GetString("AlmacenaDocumentoEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert into cdifac.tfac043(gcicod,ftifac,gnufac,ffsopr,ffaopr,ffmopr,ffdopr,fhoopr,ftxerr,fstenv) values (&apos;{0}&apos;,&apos;{1}&apos;,&apos;{2}&apos;,&apos;{3}&apos;,&apos;{4}&apos;,&apos;{5}&apos;,&apos;{6}&apos;,&apos;{7}&apos;,&apos;{8}&apos;,&apos;{9}&apos;).
        /// </summary>
        internal static string AlmacenaNoAceptadas {
            get {
                return ResourceManager.GetString("AlmacenaNoAceptadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select fsrfac as caja from intfac.ffac007 where gcicod = &apos;{0}&apos; and fcoprt=&apos;{1}&apos;.
        /// </summary>
        internal static string CajaFactura {
            get {
                return ResourceManager.GetString("CajaFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        /// cdf.vsrfac as SERIE, aut2.fcisat AS EMPRESA, aut2.fessat AS GSUCOD, aut2.fcocaj AS CAJA, aut.vcomar
        ///from vhl.vhlfc2 aut  join vhl.vhlcdf cdf
        ///on cdf.vcoeim=aut.vcocio and cdf.vcogrm=aut.vcogrm inner join cdifac.tfac048 aut2
        ///on aut2.vcocio=aut.vcocia and aut2.vcomar=aut.vcomar
        ///where aut.vtidoc&lt;&gt;&apos;9&apos;
        ///and aut.vnufav=&apos;{0}&apos;.
        /// </summary>
        internal static string CESS {
            get {
                return ResourceManager.GetString("CESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select gcicod,anudoc,atiopr,gcocla,gsucod,gmacod,gigcod,avltot from libusr.cta006l9 where anudoc=&apos;{0}&apos; and atiopr=&apos;{1}&apos;.
        /// </summary>
        internal static string CuentasCargoAbono {
            get {
                return ResourceManager.GetString("CuentasCargoAbono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select distinct(fcisat) as empresa from cdifac.tfac046 where gcicod=&apos;{0}&apos;.
        /// </summary>
        internal static string DatosSAT {
            get {
                return ResourceManager.GetString("DatosSAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select fcisat as empresa, fessat as sucursal, fcocaj as caja from cdifac.tfac048 where vcocio=&apos;{0}&apos; and vcomar=&apos;{1}&apos; and vsrdoc=&apos;{2}&apos;.
        /// </summary>
        internal static string DatosSATVOFN {
            get {
                return ResourceManager.GetString("DatosSATVOFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select &apos;0&apos; as descuento, sum(abs(gpvfac)) as subtotal from PGMDATOS.NGEN051FYN where gcicod=&apos;{0}&apos; {1} and gnufac=&apos;{2}&apos;.
        /// </summary>
        internal static string DescuentoSubTotal_Servicios {
            get {
                return ResourceManager.GetString("DescuentoSubTotal_Servicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select &apos;0&apos; as descuento, sum(abs(gpvfac)) as subtotal from PGMDATOS.NGEN051FYN where gcicod=&apos;{0}&apos; {1} and gnufac=&apos;{2}&apos;.
        /// </summary>
        internal static string DescuentoSubTotal_Servicios_NCR {
            get {
                return ResourceManager.GetString("DescuentoSubTotal_Servicios_NCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///gcamov as CANTIDAD
        ///, &apos;&apos; as METRICA
        ///, fdeart as DESCRIPCION
        ///, fpruni as PRECIOUNITARIO
        ///,decimal(gpvfac,9,2) as VALOR
        ///,ggpcod || &apos; &apos; || gcoart as DETALLE1
        ///from cdifac.tfac052 
        ///where gcicod=&apos;{0}&apos; and trim(gnufac)=&apos;{1}&apos;.
        /// </summary>
        internal static string DETALLE_TFAC052 {
            get {
                return ResourceManager.GetString("DETALLE_TFAC052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select &apos;0&apos; as CANTIDAD, &apos;&apos; AS METRICA, &apos;0&apos; AS PRECIOUNITARIO, &apos;&apos; AS DETALLE1, det.vdetfav as DESCRIPCION, det.vvaldet as VALOR from vhl.tvhl168 det where det.vnufav=&apos;{0}&apos; AND EXIEIM=&apos;{1}&apos;.
        /// </summary>
        internal static string DetalleAutosNuevos {
            get {
                return ResourceManager.GetString("DetalleAutosNuevos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select &apos;0&apos; as CANTIDAD, &apos;&apos; AS METRICA, &apos;0&apos; AS PRECIOUNITARIO, &apos;&apos; AS DETALLE1, det.vdetfav as DESCRIPCION, det.vvaldet as VALOR 
        ///from cdivus.tvUS020 det where concat(trim(substr(trim(det.vnufav),1,1)),trim(substr(trim(det.vnufav),2))) =&apos;{0}&apos;.
        /// </summary>
        internal static string DetalleAutosUsados {
            get {
                return ResourceManager.GetString("DetalleAutosUsados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///det.gcamov as CANTIDAD
        ///, art.gcaumv as METRICA
        ///, art.gnmart as DESCRIPCION
        ///,round((det.gpvfa$/det.gcamov),2) as PRECIOUNITARIO
        ///,round(decimal(abs(det.gpvfa$),9,2),2) as VALOR
        ///, art.ggpcod || &apos; &apos; || art.gcoart as DETALLE1 ,round(decimal(abs(det.ipvmov),9,2),2) as VALOR2, round((det.ipvmov/det.gcamov),2) as PRECIOUNITARIO2
        ///from pgmdatos.ngen051CS det left join intgen.fgen016 art 
        ///on det.gcicod=art.gcicod and det.icotip=art.icotip and det.gcoart=art.gcoart
        ///where det.gcicod=&apos;{0}&apos; {1} and det.gn [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string DetalleNCR {
            get {
                return ResourceManager.GetString("DetalleNCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///&apos;1.00&apos; as CANTIDAD
        ///, &apos;&apos; as METRICA
        ///, det.gnmart as DESCRIPCION
        ///,&apos;0.00&apos; as PRECIOUNITARIO
        ///,round(decimal(abs(det.gpvfac),9,2),2) as VALOR
        ///,&apos; &apos; as DETALLE1
        ///from PGMDATOS.NGEN051FYN det 
        ///where det.gcicod=&apos;{0}&apos; {1} and det.gnufac=&apos;{2}&apos;.
        /// </summary>
        internal static string DetalleNCR_TS {
            get {
                return ResourceManager.GetString("DetalleNCR_TS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select &apos;0&apos; as CANTIDAD, &apos;&apos; as METRICA, ofi.vdetpl as DESCRIPCION, &apos;0&apos; AS PRECIOUNITARIO, ofi.vvdepl as VALOR, &apos;&apos; as DETALLE1 from vhl.vhldfn ofi WHERE VDOFYN=&apos;{0}&apos; AND VCOEIM=&apos;{1}&apos;.
        /// </summary>
        internal static string DetalleOficina {
            get {
                return ResourceManager.GetString("DetalleOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select gcicod, gnufac, rnusec, rderub, rvarub  from cdirep.trep146 where gcicod = &apos;{0}&apos; and gnufac = &apos;{1}&apos; order by rnusec asc.
        /// </summary>
        internal static string DetalleRep146 {
            get {
                return ResourceManager.GetString("DetalleRep146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///det.gcamov as CANTIDAD
        ///, art.gcaumv as METRICA
        ///, art.gnmart as DESCRIPCION
        ///,round((det.gpvfa$/det.gcamov),2) as PRECIOUNITARIO
        ///,round(decimal(det.gpvfa$,9,2),2) as VALOR
        ///, art.ggpcod || &apos; &apos; || art.gcoart as DETALLE1
        ///from pgmdatos.ngen051CS det left join intgen.fgen016 art 
        ///on det.gcicod=art.gcicod and det.icotip=art.icotip and det.gcoart=art.gcoart
        ///where det.gcicod=&apos;{0}&apos; {1} and det.gnufac=&apos;{2}&apos;.
        /// </summary>
        internal static string DetalleRepuestos_FAC {
            get {
                return ResourceManager.GetString("DetalleRepuestos_FAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///det.icamov as CANTIDAD
        ///, art.gcaumv as METRICA
        ///, art.gnmart as DESCRIPCION
        ///,round(decimal(det.ipvmov)/decimal(det.icamov)*1.12,2) as PRECIOUNITARIO
        ///,round(decimal(det.ipvmov,9,2)*1.12,2) as VALOR
        ///, art.ggpcod || &apos; &apos; || art.gcoart as DETALLE1
        ///from intinv.finv003 det left join intgen.fgen016 art 
        ///on det.gcicod=art.gcicod and det.icotip=art.icotip and det.gcoart=art.gcoart
        ///where det.gcicod=&apos;{0}&apos; {1} and det.itimov=&apos;{2}&apos; and det.inumov=&apos;{3}&apos;.
        /// </summary>
        internal static string DetalleRepuestos_NR {
            get {
                return ResourceManager.GetString("DetalleRepuestos_NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///&apos;1.00&apos; as CANTIDAD
        ///, &apos;&apos; as METRICA
        ///, &apos;Repuestos Utilizados en Taller&apos; as DESCRIPCION
        ///,&apos;0.00&apos; as PRECIOUNITARIO
        ///, sum(det.ipvmov) as VALOR
        ///, &apos;&apos; as DETALLE1
        ///from intinv.finv003 det left join intgen.fgen016 art 
        ///on det.gcicod=art.gcicod and det.icotip=art.icotip and det.gcoart=art.gcoart
        ///where det.gcicod=&apos;{0}&apos; {1} and det.itimov=&apos;{2}&apos; and det.inumov=&apos;{3}&apos;.
        /// </summary>
        internal static string DetalleRepuestos_TR {
            get {
                return ResourceManager.GetString("DetalleRepuestos_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///&apos;1.00&apos; as CANTIDAD
        ///, &apos;&apos; as METRICA
        ///, &apos;Repuestos Utilizados en Taller&apos; as DESCRIPCION
        ///,&apos;0.00&apos; as PRECIOUNITARIO
        ///, round(sum(decimal(det.gpvfa$,9,2)),2) as VALOR
        ///, &apos;&apos; as DETALLE1
        ///from pgmdatos.ngen051CS det 
        ///where det.gcicod=&apos;{0}&apos; {1} and det.gnufac=&apos;{2}&apos;.
        /// </summary>
        internal static string DetalleRepuestos_TR_Opt {
            get {
                return ResourceManager.GetString("DetalleRepuestos_TR_Opt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///&apos;1.00&apos; as CANTIDAD
        ///, &apos;&apos; as METRICA
        ///, det.gnmart as DESCRIPCION
        ///,&apos;0.00&apos; as PRECIOUNITARIO
        ///,round(decimal(det.gpvfac,9,2),2) as VALOR
        ///,&apos; &apos; as DETALLE1
        ///from PGMDATOS.NGEN051FYN det 
        ///where det.gcicod=&apos;{0}&apos; {1} and det.gnufac=&apos;{2}&apos;.
        /// </summary>
        internal static string DetalleServicios {
            get {
                return ResourceManager.GetString("DetalleServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///trim(gnufac) as gnufac,
        ///icotip,
        ///gcocaj as CAJA,
        ///gclnom as NOMBRECONTRIBUYENTE,
        ///(gcldir || gclcol || gcledi) as DIRECCIONCONTRIBUYENTE,
        /// case gfsfac 
        ///	when &apos;0&apos; then gfdfac||&apos;-&apos;||gfmfac||&apos;-19&apos;||gfafac||&apos; &apos;||substring(trim(RIGHT(&apos;000000&apos;||gfahor,6)),1,2)||&apos;:&apos;||substring(trim(RIGHT(&apos;000000&apos;||gfahor,6)),3,2)||&apos;:&apos;||substring(trim(RIGHT(&apos;000000&apos;||gfahor,6)),5,2)
        ///  	when &apos;1&apos; then gfdfac||&apos;-&apos;||gfmfac||&apos;-20&apos;||gfafac||&apos; &apos;||substring(trim(RIGHT(&apos;000000&apos;||gfahor,6)),1,2)||&apos;:&apos;||substring(trim(RIGHT(&apos;00000 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ENCABEZADO_TFAC051 {
            get {
                return ResourceManager.GetString("ENCABEZADO_TFAC051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///substr(aut.vnufav,length(trim(cdf.vsrfac))+1,length(trim(aut.vnufav))) as NOFACTURA
        ///, aut.vnufav as GNUFAC
        ///, cdf.vsrfac as SERIE
        ///, aut.vclnom as NOMBRECONTRIBUYENTE
        ///, case aut.v@ste2 when &apos;&apos; then &apos;GTQ&apos;
        ///                  WHEN &apos;DO&apos;THEN &apos;USD&apos;
        ///  END as MONEDA
        ///, (trim(COALESCE(aut.vcldir,&apos;&apos;))||trim(COALESCE(aut.vclcol,&apos;&apos;))||trim(COALESCE(aut.vcledi,&apos;&apos;))) as DIRECCIONCONTRIBUYENTE
        ///, aut.vfdfav||&apos;/&apos;||aut.vfmfav||&apos;/&apos;||aut.vfafav as FECHAEMISION
        ///, decimal(aut.vvaiva,9,2) as IVA
        ///, &apos;0.00&apos; AS EXENTO        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string EncabezadoAutosNuevos {
            get {
                return ResourceManager.GetString("EncabezadoAutosNuevos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///substr(aut.vnufav,2,length(trim(aut.vnufav))) as NOFACTURA
        ///, substr(trim(aut.vnufav),0,2) as SERIE
        ///, aut.vclnom as NOMBRECONTRIBUYENTE
        ///, &apos;GTQ&apos; as MONEDA
        ///, (COALESCE(aut.VCLDIR,&apos;&apos;)||COALESCE(aut.VCLCOL,&apos;&apos;)||COALESCE(aut.v@dciu,&apos;&apos;)) as DIRECCIONCONTRIBUYENTE
        ///, aut.vfdfav||&apos;/&apos;||aut.vfmfav||&apos;/&apos;||aut.vfafav as FECHAEMISION
        ///, aut.vvaiva as IVA
        ///, &apos;0.00&apos; AS EXENTO
        ///, aut.vvanet AS VALORNETO
        ///, aut.vvabru as TOTAL
        ///, &apos;0&apos; AS DESCUENTO
        ///, aut.vclnit as NITCONTRIBUYENTE
        ///, usr.vcofcr as USUARIO, &apos;&apos; as V [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string EncabezadoAutosUsados {
            get {
                return ResourceManager.GetString("EncabezadoAutosUsados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        /// ofi.vdofyn
        ///, substr(ofi.vdofyn,4,length(trim(ofi.vdofyn))) as NOFACTURA3
        ///, substr(ofi.vdofyn,3,length(trim(ofi.vdofyn))) as NOFACTURA2
        ///, substr(ofi.vdofyn,2,length(trim(ofi.vdofyn))) as NOFACTURA
        ///, substr(trim(ofi.vdofyn),0,4) as SERIE3
        ///, substr(trim(ofi.vdofyn),0,2) as SERIE
        ///, substr(trim(ofi.vdofyn),0,3) as SERIE2
        ///, &apos;GTQ&apos; as MONEDA
        ///, ofi.vclnom as NOMBRECONTRIBUYENTE
        ///, (COALESCE(ofi.vcldi1,&apos;&apos;)||COALESCE(ofi.vcldi2,&apos;&apos;)||COALESCE(ofi.vcldi3,&apos;&apos;)) as DIRECCIONCONTRIBUYENTE
        ///, ofi.vfdfyn||&apos;/ [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string EncabezadoOficina {
            get {
                return ResourceManager.GetString("EncabezadoOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///enc.gnufac AS GNUFAC,
        ///enc.icotip
        ///, enc.gcocaj as CAJA
        ///, enc.gclnom as NOMBRECONTRIBUYENTE
        ///, (enc.gcldir || enc.gclcol || enc.gcledi) as DIRECCIONCONTRIBUYENTE
        ///, case enc.gfsfac 
        ///	when &apos;0&apos; then enc.gfdfac||&apos;-&apos;||enc.gfmfac||&apos;-19&apos;||enc.gfafac
        ///  	when &apos;1&apos; then enc.gfdfac||&apos;-&apos;||enc.gfmfac||&apos;-20&apos;||enc.gfafac
        ///  end as FECHAEMISION
        ///, enc.givfac AS IVA
        ///, enc.gvnfac as VALORNETO
        ///, enc.gvtfac as TOTAL
        ///,  &apos;0.00&apos; as DESCUENTO
        ///, enc.gclnit as NITCONTRIBUYENTE
        ///, cajero.ocjnom as USUARIO
        ///, enc.gflex [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string EncabezadoRep_nuevo {
            get {
                return ResourceManager.GetString("EncabezadoRep_nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///enc.gnufac AS GNUFAC,
        ///enc.icotip
        ///, enc.gcocaj as CAJA
        ///, enc.gclnom as NOMBRECONTRIBUYENTE
        ///, (enc.gcldir || enc.gclcol || enc.gcledi) as DIRECCIONCONTRIBUYENTE
        ///, case enc.gfsfac 
        ///	when &apos;0&apos; then enc.gfdfac||&apos;-&apos;||enc.gfmfac||&apos;-19&apos;||enc.gfafac
        ///  	when &apos;1&apos; then enc.gfdfac||&apos;-&apos;||enc.gfmfac||&apos;-20&apos;||enc.gfafac
        ///  end as FECHAEMISION
        ///, enc.givfac AS IVA
        ///, enc.gvnfac as VALORNETO
        ///, enc.gvtfac as TOTAL
        ///,  case enc.gdcfac 
        ///	when &apos;0&apos; then &apos;0&apos;
        ///	else round((decimal(enc.gdcfac,9,2)+(decimal(enc.givfac [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string EncabezadoRepuestos {
            get {
                return ResourceManager.GetString("EncabezadoRepuestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///  trim(gflanu) as estado
        ///  from cdifac.tfac051 nolock
        ///  where gfancr=&apos;{0}&apos; and gcicod=&apos;{1}&apos; and trim(gnufac)=&apos;{2}&apos;
        ///union
        ///select 
        ///	trim(vstfc1) as estado
        ///	from vhl.vhlfc2 nolock
        ///	where vtidoc&lt;&gt;&apos;9&apos; and vtiopr=&apos;1&apos; and vcocio=&apos;{1}&apos; and trim(vnufav)=&apos;{2}&apos;
        ///union
        ///select 
        ///	ofi.vstfyn as estado
        ///	from vhl.vhlfyn ofi inner join vhl.vhlfc2 aut
        ///	on aut.vcocio=ofi.vcoeim and aut.vnufav=ofi.vdoref
        ///	where ofi.vcoeim=&apos;{1}&apos; and ofi.vplfyn=&apos;VEH&apos; and aut.vtidoc&lt;&gt;&apos;9&apos; and trim(vdofyn)=&apos;{2}&apos;
        ///union
        ///select         /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string EstadoDocumento {
            get {
                return ResourceManager.GetString("EstadoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select rorfac, case rfsfac 
        ///	when &apos;0&apos; then rfdfac||&apos;-&apos;||rfmfac||&apos;-19&apos;||rfafac
        ///  	when &apos;1&apos; then rfdfac||&apos;-&apos;||rfmfac||&apos;-20&apos;||rfafac end from intrep.frep137 where rornum = &apos;{0}&apos; AND gfancr = {1} and rvtfac = {2}.
        /// </summary>
        internal static string FacturaReferencia {
            get {
                return ResourceManager.GetString("FacturaReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update cdifac.tfac045 set fnuenv = &apos;{0}&apos; where gcicod = &apos;{1}&apos; and ftifac = &apos;{2}&apos;.
        /// </summary>
        internal static string IncrementaLote {
            get {
                return ResourceManager.GetString("IncrementaLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select trim(gnufac) as no_doc, gfldtq as procesada, gtifac as tipo, gflanu as estado from cdifac.tfac051
        ///where gfancr=&apos;{0}&apos; and gcicod=&apos;{1}&apos; {2} and gtifac{3}&apos;TS&apos;
        ///and (gfdfac between &apos;{4}&apos; and &apos;{5}&apos;)
        ///and (gfmfac between &apos;{6}&apos; and &apos;{7}&apos;)
        ///and (gfafac between &apos;{8}&apos; and &apos;{9}&apos;) order by no_doc asc.
        /// </summary>
        internal static string LoteDocumentos {
            get {
                return ResourceManager.GetString("LoteDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT aut.vnufav AS NO_DOC, aut.vstfc1 as ESTADO, &apos;&apos; as PROCESADA, (cta.afddoc||&apos;/&apos;||cta.afmdoc||&apos;/&apos;||cta.afadoc) as fecha
        ///FROM vhl.vhlfc2 aut inner join intcta.fcta006 cta 
        ///on  aut.vcocio=cta.gcicod and aut.vnufav=cta.anudoc and aut.vtiopr=cta.atiopr
        ///where
        ///aut.vtidoc&lt;&gt;&apos;9&apos; and aut.vtiopr=&apos;1&apos; and aut.vcocio=&apos;{0}&apos;
        ///and (cta.afddoc between &apos;{1}&apos; and &apos;{2}&apos; ) 
        ///and (cta.afmdoc between &apos;{3}&apos; and &apos;{4}&apos; ) 
        ///and (cta.afadoc between &apos;{5}&apos; and &apos;{6}&apos; ) 
        ///group by aut.vnufav,cta.afddoc,cta.afmdoc,cta.afadoc,aut.vst [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string LoteDocumentosFVH {
            get {
                return ResourceManager.GetString("LoteDocumentosFVH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT cta.anudoc AS NO_DOC, aut.vstfc1 as ESTADO, &apos;&apos; as PROCESADA, (cta.afddoc||&apos;/&apos;||cta.afmdoc||&apos;/&apos;||cta.afadoc) as fecha
        ///FROM intcta.fcta006 cta inner join cdivus.vusfc2 aut 
        ///on aut.vnufav=cta.anudoc
        ///where
        ///aut.vtidoc&lt;&gt;&apos;8&apos; and aut.vtiopr=&apos;1&apos; and trim(aut.vcocia)=&apos;AM&apos; and v@ste2 in ({6})  and substr(trim(aut.vnufav),0,2)=&apos;{7}&apos; 
        ///and (cta.afddoc between &apos;{0}&apos; and &apos;{1}&apos; ) 
        ///and (cta.afmdoc between &apos;{2}&apos; and &apos;{3}&apos; ) 
        ///and (cta.afadoc between &apos;{4}&apos; and &apos;{5}&apos; ) 
        ///group by cta.anudoc,cta.afddoc,cta.afmdoc,ct [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string LoteDocumentosFVU {
            get {
                return ResourceManager.GetString("LoteDocumentosFVU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///ofi.vdofyn AS NO_DOC
        ///,ofi.vstfyn as ESTADO
        ///, &apos;&apos; as PROCESADA
        ///from vhl.vhlfyn ofi inner join vhl.vhlfc2 aut
        ///on aut.vcocio=ofi.vcoeim and aut.vnufav=ofi.vdoref
        ///where ofi.vcoeim=&apos;{0}&apos; and ofi.vplfyn=&apos;VEH&apos; and aut.vtidoc&lt;&gt;&apos;9&apos;
        ///and (ofi.vfdfyn between &apos;{1}&apos; and &apos;{2}&apos;)
        ///and (ofi.vfmfyn between &apos;{3}&apos; and &apos;{4}&apos;)
        ///and (ofi.vfafyn between &apos;{5}&apos; and &apos;{6}&apos;) order by no_doc asc.
        /// </summary>
        internal static string LoteDocumentosNVH {
            get {
                return ResourceManager.GetString("LoteDocumentosNVH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///ofi.vdofyn AS NO_DOC
        ///,ofi.vstfyn as ESTADO
        ///, &apos;&apos; as PROCESADA
        ///from vhl.vhlfyn ofi inner join  cdivus.vusfc2 aut
        ///on aut.vnufav=ofi.vdofyn
        ///where ofi.vcoeim=&apos;{0}&apos; and ofi.vplfyn=&apos;VEH&apos; and aut.vtidoc&lt;&gt;&apos;8&apos; 
        ///and (ofi.vfdfyn between &apos;{1}&apos; and &apos;{2}&apos;)
        ///and (ofi.vfmfyn between &apos;{3}&apos; and &apos;{4}&apos;)
        ///and (ofi.vfafyn between &apos;{5}&apos; and &apos;{6}&apos;) order by no_doc asc.
        /// </summary>
        internal static string LoteDocumentosNVU {
            get {
                return ResourceManager.GetString("LoteDocumentosNVU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///ofi.vdofyn AS NO_DOC
        ///,ofi.vstfyn as ESTADO
        ///, &apos;&apos; as PROCESADA
        ///from vhl.vhlfyn ofi 
        ///where ofi.vcoeim=&apos;{0}&apos; and ofi.vplfyn&lt;&gt;&apos;VEH&apos; and ofi.vtifyn=&apos;{1}&apos;
        ///and (ofi.vfdfyn between &apos;{2}&apos; and &apos;{3}&apos;)
        ///and (ofi.vfmfyn between &apos;{4}&apos; and &apos;{5}&apos;)
        ///and (ofi.vfafyn between &apos;{6}&apos; and &apos;{7}&apos;) order by no_doc asc.
        /// </summary>
        internal static string LoteDocumentosOficina {
            get {
                return ResourceManager.GetString("LoteDocumentosOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///substr(ofi.vdofyn,length(trim(cfn.vsefyn))+1,length(trim(ofi.vdofyn))) as NOFACTURA, cfn.vsefyn as IDSERIE, ofi.vfdfyn||&apos;/&apos;||ofi.vfmfyn||&apos;/&apos;||ofi.vfafyn as FECHAFACTURA
        ///from vhl.vhlfyn ofi inner join vhl.vhlcfn cfn
        ///on cfn.vcoeim=ofi.vcoeim and cfn.vtifyn=ofi.vtifyn and cfn.vcogrm=ofi.vcogrm
        ///where ofi.vdofyn=&apos;{0}&apos; and ofi.vcoeim={1}
        ///union
        ///select 
        ///substr(aut.vnufav,length(trim(cdf.vsrfac))+1,length(trim(aut.vnufav))) as NOFACTURA, cdf.vsrfac as IDSERIE, aut.vfdfav||&apos;/&apos;||aut.vfmfav||&apos;/&apos;||aut.vfa [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string NumeroFacturaSerie {
            get {
                return ResourceManager.GetString("NumeroFacturaSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select fnuenv as numlot from cdifac.tfac045 where gcicod = &apos;{0}&apos; and ftifac = &apos;{1}&apos;.
        /// </summary>
        internal static string NumeroLote {
            get {
                return ResourceManager.GetString("NumeroLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select (sum(gpvfa$)-sum(ipvmod)) as descuento, sum(gpvfa$) as subtotal from pgmdatos.ngen051CS where gcicod=&apos;{0}&apos; {1} and gnufac=&apos;{2}&apos;.
        /// </summary>
        internal static string ObtieneDescuentoSubTotal {
            get {
                return ResourceManager.GetString("ObtieneDescuentoSubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///aut.vcoclf as OPCIONAL1
        ///, aut.vcodes as OPCIONAL2
        ///, &apos;&apos; as OPCIONAL3
        ///, COALESCE(fpor.vcofcr,&apos;&apos;) as OPCIONAL4
        ///, COALESCE(vpor.vncven,&apos;&apos;) as OPCIONAL5
        ///, &apos;&apos; as OPCIONAL6
        ///, &apos;&apos; as OPCIONAL7
        ///, &apos;&apos; as OPCIONAL8
        ///, decimal((decimal(aut.vvanet,9,2)+decimal(COALESCE(descuento.vvaldet,&apos;0&apos;),9,2)),9,2) as OPCIONAL9
        ///, &apos;&apos; as TELEFONO
        ///from vhl.vhlfc2 aut left join vhl.vhlfcr fpor
        ///on fpor.VCOFCR=aut.vcofcr left join vhl.vhlven vpor
        ///on vpor.vcoven=aut.vcoven left join vhl.tvhl168 descuento 
        ///on descuento.vn [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string OpcionalAutosNuevos {
            get {
                return ResourceManager.GetString("OpcionalAutosNuevos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///aut.vcoclf as OPCIONAL1
        ///, &apos;&apos; as OPCIONAL2
        ///, coalesce(fin.vsigla,case aut.vcocre when &apos;&apos; then &apos;CONTADO&apos; when &apos;R&apos; then &apos;CREDITO&apos; END) as OPCIONAL3
        ///, COALESCE(fpor.vcofcr,&apos;&apos;) as OPCIONAL4
        ///, case aut.vtidoc when &apos;9&apos; then &apos;&apos; else COALESCE(vpor.vncven,&apos;&apos;) end as OPCIONAL5
        ///, &apos;&apos; as OPCIONAL6
        ///, &apos;&apos; as OPCIONAL7
        ///, &apos;&apos; as OPCIONAL8
        ///, &apos;&apos; as OPCIONAL9
        ///, aut.vcocre
        ///, aut.vtidoc
        ///from cdivus.vusfc2 aut left join vhl.vhlfcr fpor
        ///on fpor.VCOFCR=aut.vcofcr left join vhl.vhlven vpor
        ///on vpor.vcoven=aut.vcove [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string OpcionalAutosUsados {
            get {
                return ResourceManager.GetString("OpcionalAutosUsados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        /// gclcod as OPCIONAL1
        ///, rornum as OPCIONAL2
        ///, trim(gtipag)||&apos;  &apos;|| case trim(fcadia) when &apos;0&apos; then &apos;&apos; else trim(fcadia) end as OPCIONAL3
        ///, ocjnom as OPCIONAL4
        ///, gcoven as OPCIONAL5
        ///, ltrim(rtrim(favi00))||&apos; &apos;||ltrim(rtrim(favi01))||&apos; &apos;||ltrim(rtrim(favi02))||&apos; &apos;||ltrim(rtrim(favi03))||&apos; &apos;||ltrim(rtrim(favi04))||&apos; &apos;||ltrim(rtrim(fobs01))||&apos; &apos;||ltrim(rtrim(fcom01))||&apos; &apos;||ltrim(rtrim(fcom02)) as OPCIONAL6
        ///, trim(gnufac) as OPCIONAL7
        ///, ftxord as OPCIONAL8
        ///, fsbfai as OPCIONAL9
        ///from cdifac.tfac0 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string OPCIONALES_TFAC051 {
            get {
                return ResourceManager.GetString("OPCIONALES_TFAC051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        ///ofi.vcocli as OPCIONAL1
        ///, &apos;&apos; as OPCIONAL2
        ///, &apos;CREDITO&apos; as OPCIONAL3
        ///, ofi.vusfyn as OPCIONAL4
        ///, &apos;&apos; as OPCIONAL5
        ///, &apos;&apos; as OPCIONAL6
        ///, &apos;&apos; as OPCIONAL7
        ///, &apos;&apos; as OPCIONAL8
        ///, &apos;&apos; as OPCIONAL9
        ///, &apos;&apos; as TELEFONO
        ///from vhl.vhlfyn ofi
        ///where ofi.vdofyn=&apos;{0}&apos; and ofi.vtifyn=&apos;{1}&apos; and ofi.vstfyn=&apos;{2}&apos;.
        /// </summary>
        internal static string OpcionalOficina {
            get {
                return ResourceManager.GetString("OpcionalOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        /// enc.gclcod as OPCIONAL1
        ///, &apos;&apos; as OPCIONAL2
        ///, enc.gtipag as OPCIONAL3
        ///, caj.ocjnom as OPCIONAL4
        ///, ven.gcoven as OPCIONAL5
        ///, &apos;&apos; as OPCIONAL6
        ///, ord.rornum as OPCIONAL7
        ///, &apos;&apos; as OPCIONAL8
        ///, &apos;0.00&apos; as OPCIONAL9
        ///from libusr.gen038lq enc left join intfac.fcaj014 caj
        ///on enc.gcicod=caj.gcicod and enc.gcocaj=caj.gcocaj left join intgen.fgen029 ven
        ///on enc.gcicod=ven.gcicod and enc.gcoven=ven.gcoven left join intrep.frep110 ord on enc.gcicod=ord.gcicod and enc.gnufac=ord.rorfac
        ///where enc.gfancr=&apos;{0} [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string OpcionalRep_Nuevo {
            get {
                return ResourceManager.GetString("OpcionalRep_Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select 
        /// enc.gclcod as OPCIONAL1
        ///, &apos;&apos; as OPCIONAL2
        ///, enc.gtipag as OPCIONAL3
        ///, caj.ocjnom as OPCIONAL4
        ///, COALESCE(ven.gnmven,&apos;&apos;) as OPCIONAL5
        ///, &apos;&apos; as OPCIONAL6
        ///, ord.rornum as OPCIONAL7
        ///, &apos;&apos; as OPCIONAL8
        ///, decimal((decimal(enc.gvnfac,9,2)+decimal(enc.givfac,9,2)+decimal((decimal(enc.gdcfac,9,2)+(decimal(enc.givfac,9,2)-decimal(poriva.gpgivv,9,2)/100*(decimal(enc.gvnfac,9,2) - decimal(enc.gdcfac,9,2)))),9,2)),9,2) as OPCIONAL9
        ///from libusr.gen038lq enc left join intfac.fcaj014 caj
        ///on enc.gcicod=caj [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string OpcionalRepuestos {
            get {
                return ResourceManager.GetString("OpcionalRepuestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select * from SSO_GFC_FAC_SERIE where IdEmpresa={0} and idserie=&apos;{1}&apos;.
        /// </summary>
        internal static string SerieFAC {
            get {
                return ResourceManager.GetString("SerieFAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select * from SSO_GFC_NC_SERIE where IdEmpresa={0} and idserie=&apos;{1}&apos;.
        /// </summary>
        internal static string SerieNCR {
            get {
                return ResourceManager.GetString("SerieNCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select a.SERIE as SERIE from (
        ///select distinct(trim(fsrcom)) AS SERIE from intfac.ffac007 where trim(fsrcom) &lt;&gt; &apos;&apos; 
        ///UNION
        ///SELECT distinct(trim(GSRNCR)) AS SERIE FROM INTGEN.FGEN022 where trim(gsrncr) &lt;&gt; &apos;&apos; 
        ///UNION 
        ///select distinct(trim(rsrncr)) AS SERIE from CDIFAC.TFAC050 where trim(rsrncr) &lt;&gt;&apos;&apos; 
        ///) a order by length(a.SERIE) desc.
        /// </summary>
        internal static string SeriesFgen038 {
            get {
                return ResourceManager.GetString("SeriesFgen038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select substr(ofi.vdofyn,length(trim(cfn.vsefyn))+1,length(trim(ofi.vdofyn))) as NOFACTURA, cfn.vsefyn as IDSERIE, ofi.vfdfyn||&apos;/&apos;||ofi.vfmfyn||&apos;/&apos;||ofi.vfafyn as FECHAFACTURA
        ///from vhl.vhlfyn ofi inner join vhl.vhlcfn cfn
        ///on cfn.vcoeim=ofi.vcoeim and cfn.vtifyn=ofi.vtifyn and cfn.vcogrm=ofi.vcogrm
        ///where ofi.vdofyn=&apos;{0}&apos;
        ///union
        ///select 
        ///substr(aut.vnufav,length(trim(cdf.vsrfac))+1,length(trim(aut.vnufav))) as NOFACTURA, cdf.vsrfac as IDSERIE, aut.vfdfav||&apos;/&apos;||aut.vfmfav||&apos;/&apos;||aut.vfafav as FECHAFACTURA
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SerieVehiculoNuevo {
            get {
                return ResourceManager.GetString("SerieVehiculoNuevo", resourceCulture);
            }
        }
    }
}
